[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["zxb"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
